#!/bin/sh

echo "Running Checkstyle..."
./gradlew -q checkstyleMain

if [ $? -ne 0 ]; then
    echo "Checkstyle failed. Commit aborted."
    exit 1
fi

echo "Checkstyle passed. Commit allowed."
exit 0
